# JavaScript的错误处理和调试
```js
try {
    // 可能会导致错误的代码
} catch {
    // 在错误发生时怎么处理
}
```
> 如果`try`块中的任何代码发生错误，就会立即退出代码执行过程，然后接着执行`catch`块，此时`catch`块会接收到一个包含错误信息的对象。